version: '3'
services: 
    selenium:
        image: selenium/standalone-chrome
        ports: 
            - 4412:4444
        restart: always
    
    bot:
        build: 
            context: .
        volumes: 
            - ./app:/app
        depends_on: 
            - selenium
